CREATE_ARTICLE_VIEW_NAME = 'create'
DELETE_ARTICLE_VIEW_NAME = 'delete_article'
UPDATE_ARTICLE_VIEW_NAME = 'update_article'
VOIR_ARTICLE_VIEW_NAME = 'voir_article'


CREATE_ARTICLE_URL  = 'shop:'+CREATE_ARTICLE_VIEW_NAME
DELETE_ARTICLE_URL = 'shop:'+DELETE_ARTICLE_VIEW_NAME
UPDATE_ARTICLE_URL = 'shop:'+UPDATE_ARTICLE_VIEW_NAME
VOIR_ARTICLE_URL = 'shop:'+VOIR_ARTICLE_VIEW_NAME