
LOGIN_VIEW_NAME = 'login'
LOGOUT_VIEW_NAME = 'logout'
REGISTER_VIEW_NAME = 'register'
UPDATE_PROFIL_VIEW_NAME = 'update_profile'
USER_PROFIL_VIEW_NAME = 'user_profile'
USER_PROFILE_INFORMATIONS = 'user_info'

LOGIN_URL_BY_APP_NAME= 'account:'+ LOGIN_VIEW_NAME
LOGOUT_URL_BY_APP_NAME= 'account:'+ LOGOUT_VIEW_NAME
REGISTER_URL_BY_APP_NAME = 'account:'+ REGISTER_VIEW_NAME
USER_PROFIL_URL_BY_APP_NAME = 'account:' + USER_PROFIL_VIEW_NAME
USER_PROFIL_INFO_URL_BY_APP_NAME = 'account:' + USER_PROFILE_INFORMATIONS
UPDATE_PROFIL_URL_BY_APP_NAME = 'account:'+ UPDATE_PROFIL_VIEW_NAME

