# Generated by Django 4.1.3 on 2023-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_article_is_send_alter_categorie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.CharField(default='BZ', max_length=50, verbose_name='ville'),
        ),
    ]
