# Generated by Django 4.1.3 on 2023-03-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_categorie_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default=None, upload_to='CategoryPhoto'),
        ),
    ]
