# Generated by Django 4.1.3 on 2023-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='../account/static/images/tekissababy.png', upload_to='CategoryPhoto'),
        ),
    ]
