# Generated by Django 4.1.3 on 2023-04-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(max_length=15, verbose_name='Nom'),
        ),
    ]
