# Generated by Django 4.1.3 on 2023-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaires',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='commentaires',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
